name="Tony Stark"
print(name)
# name.upper()
# name.lower()
# name.find('char')
# name.find("str")
print(name.upper())
print(name.lower())
# 0
print(name.find('S'))
print(name.find('s'))
print(name.find("Star"))
print(name.find("star"))
print(name.replace("Tony Stark","Iron Man"))
print(name.replace("Stark","Shrek"))
print(name.replace('T','M'))
print(name)
# print()
# input()
print('T' in name)
print('M' in name)
print("Stark" in name)
print("Shrek" in name)