import math
x = 2
print(math.cbrt(x))
print(math.ceil(x))
print(math.cos(x))
print(math.degrees(x))
print(math.exp(x))
print(math.factorial(x))
print(math.floor(x))
print(math.gcd(x))
print(math.hypot(x))
print(math.isfinite(x))
print(math.isnan(x))
print(math.lcm(x))
print(math.log(x))
print(math.modf(x))
print(math.nan)
print(math.perm(x))
print(math.pi)
print(math.radians(x))
print(math.sin(x))
print(math.sqrt(x))
print(math.tan(x))
print(math.trunc(x))
print(math.ulp(x))