import random
print(random.random())
print(random.binomialvariate())
print(random.choice([0, 1, 2, 3, 4, 5]))
print(random.expovariate())
print(random.gauss())
print(random.normalvariate())
print(random.randint(1, 6))
print(random.seed())
print(random.triangular())
print(random.uniform(0, 7))