s1 = 'nitiaayog'
s2 = 'andquietflowsthedon'
s3 = '1234567890'
s4 = 'mke $1000 a day'
print(f"s1 = {s1}")
print(f"s2 = {s2}")
print(f"s3 = {s3}")
print(f"s4 = {s4}")
print("check isalpha() on s1, s2")
print(s1.isalpha())
print(s2.isalpha())
print("check is digit on s3, s4")
print(s3.isdigit())
print(s4.isdigit())
print("check isalnum() on s1, s2, s3, s4")
print(s1.isalnum())
print(s2.isalnum())
print(s3.isalnum())
print(s4.isalnum())
print("check islower on s1, s2")
print(s1.islower())
print(s2.islower())
print(s1.isupper())
print(s2.isupper())
print("check startswith and endswith on s2")
print(s2.startswith('and'))
print(s2.endswith('and'))