from tkinter import *
root = Tk()
root.geometry("600x400")
def data():
    name = _name.get()
    age = _age.get()
    hobbies = []
    if hobby0.get():
        hobbies.append("reading")
    if hobby1.get():
        hobbies.append("music")
    print(f"name : {name}")
    print(f"age : {age}") 
    print(f"hobbies : {hobbies}")
l1 = Label(root, text = "name : ")
l1.place(x = 40, y = 40)
_name = Entry(root)
_name.place(x = 40, y = 40)
l2 = Label(root, text = "age : ")
l1.place(x = 40, y = 70)
_age = Entry(root)
_age.place(x = 80, y = 80)
l3 = Label(root, text = "hobbies : ")
l3.place(x = 40, y = 100)
hobby0 = BooleanVar()
h1 = Checkbutton(root, text = "reading", variable = hobby0)
h1.place(x = 100, y = 100)
hobby1 = BooleanVar()
h2 = Checkbutton(root, text = "music", variable = hobby1)
h2.place(x = 100, y = 130)
age = Label(root, text = "age")
age.place(x = 50, y = 140)
age_spinbox = Spinbox(root, from_ = 1, to = 100)
age_spinbox.place(x = 100, y = 150)
b = Button(root, text = "submit", command = data)
b.place(x = 150, y = 200)
root.mainloop()
data()