s = 'the terrible tiger tore the towel'
pos = s.find('t', 0)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
pos = s.find('t', pos + 1)
print(pos, s[pos])
c = s.count('t')
s = s.replace('t', 't', c)
print(s)